import { type ColorRole } from "@star4/theme/material";
import { type CSSVarFunction, type ResolveTokens, type ValueToken } from "../utils";
import { createThemeContract } from "@vanilla-extract/css";

export type ColorTokens = Record<ColorRole, ValueToken>;

export const COLOR_TOKENS: ResolveTokens<ColorTokens, CSSVarFunction> = createThemeContract({
  highestSurface: "",
  surface: "",
  surfaceDim: "",
  surfaceBright: "",
  surfaceContainerLowest: "",
  surfaceContainerLow: "",
  surfaceContainer: "",
  surfaceContainerHigh: "",
  surfaceContainerHighest: "",
  onSurface: "",
  surfaceVariant: "",
  onSurfaceVariant: "",
  inverseSurface: "",
  inverseOnSurface: "",
  outline: "",
  outlineVariant: "",
  shadow: "",
  scrim: "",
  surfaceTint: "",
  primary: "",
  onPrimary: "",
  primaryContainer: "",
  onPrimaryContainer: "",
  inversePrimary: "",
  secondary: "",
  onSecondary: "",
  secondaryContainer: "",
  onSecondaryContainer: "",
  tertiary: "",
  onTertiary: "",
  tertiaryContainer: "",
  onTertiaryContainer: "",
  error: "",
  onError: "",
  errorContainer: "",
  onErrorContainer: "",
  primaryFixed: "",
  primaryFixedDim: "",
  onPrimaryFixed: "",
  onPrimaryFixedVariant: "",
  secondaryFixed: "",
  secondaryFixedDim: "",
  onSecondaryFixed: "",
  onSecondaryFixedVariant: "",
  tertiaryFixed: "",
  tertiaryFixedDim: "",
  onTertiaryFixed: "",
  onTertiaryFixedVariant: "",
});
